# Generated by Django 3.2.5 on 2022-02-14 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='诊断创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='诊断更新时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='诊断描述')),
                ('isFinished', models.BooleanField(default=False, verbose_name='诊断是否完成')),
                ('doctors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='医生')),
            ],
            options={
                'verbose_name': '诊断',
                'verbose_name_plural': '诊断集',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='诊断项创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='诊断项更新时间')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pathology.diagnosis', verbose_name='诊断')),
            ],
            options={
                'verbose_name': '诊断项',
                'verbose_name_plural': '诊断项集',
            },
        ),
        migrations.CreateModel(
            name='LabelItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='标注时间')),
                ('modifiedAt', models.DateTimeField(auto_now=True, verbose_name='标注更新时间')),
                ('category', models.CharField(choices=[('M', '真菌'), ('TR', '阴道滴虫'), ('AM', '放线菌'), ('CL', '线索细胞'), ('CMV', '巨细胞病毒'), ('HSV', '疱疹病毒'), ('IM', '炎症'), ('S', '萎缩'), ('ASC-US', '非典型鳞状细胞意义不明'), ('ASC-H', '非典型鳞状细胞不除外上皮高度病'), ('AGC(NSL)-CC', '非典型腺细胞(无具体指向)宫颈管'), ('AGC(NSL)-E', '非典型腺细胞(无具体指向)宫内膜'), ('AGC(NSL)-US', '非典型腺细胞(无具体指向)不能确定来源'), ('LSIL', '鳞状上皮内低度病变'), ('AGC(FN)-CC', '非典型腺细胞(倾向瘤变)宫颈管'), ('AGC(FN)-US', '非典型腺细胞(倾向瘤变)不能确定来源'), ('HSIL', '鳞状上皮内高度病变'), ('AIS', '颈管原位癌'), ('SCC', '鳞状细胞癌'), ('GC-CC', '腺癌宫颈管'), ('GC-E', '腺癌宫内膜'), ('GC-OT', '腺癌其他')], default='M', max_length=20, verbose_name='类别')),
                ('x', models.FloatField(verbose_name='标注起点坐标X')),
                ('y', models.FloatField(verbose_name='标注起点坐标Y')),
                ('w', models.FloatField(verbose_name='标注宽度')),
                ('h', models.FloatField(verbose_name='标注高度')),
                ('zoomLevel', models.FloatField(default=10.0, verbose_name='标注时放大倍数')),
                ('regionPicture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='标注区域图')),
                ('confidence', models.FloatField(default=1.0, verbose_name='自信度')),
                ('diagnosisItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pathology.diagnosisitem', verbose_name='诊断项')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='医生')),
            ],
            options={
                'verbose_name': '标注',
                'verbose_name_plural': '标注集',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='病人姓名')),
                ('sex', models.CharField(max_length=255, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '病人',
                'verbose_name_plural': '病人集',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='报告时间')),
                ('modifiedAt', models.DateTimeField(auto_now=True, verbose_name='报告更新时间')),
                ('manyi', models.BooleanField(default=False, verbose_name='满意')),
                ('jinguanxibao', models.BooleanField(default=False, verbose_name='颈管细胞')),
                ('huashengxibao', models.BooleanField(default=False, verbose_name='化生细胞')),
                ('bumanyi', models.BooleanField(default=False, verbose_name='不满意')),
                ('M', models.BooleanField(default=False, verbose_name='真菌')),
                ('TR', models.BooleanField(default=False, verbose_name='阴道滴虫')),
                ('AM', models.BooleanField(default=False, verbose_name='放线菌')),
                ('CL', models.BooleanField(default=False, verbose_name='线索细胞')),
                ('CMV', models.BooleanField(default=False, verbose_name='巨细胞病毒')),
                ('HSV', models.BooleanField(default=False, verbose_name='疱疹病毒')),
                ('IM', models.BooleanField(default=False, verbose_name='炎症')),
                ('S', models.BooleanField(default=False, verbose_name='萎缩')),
                ('ASC_US', models.BooleanField(default=False, verbose_name='非典型鳞状细胞意义不明')),
                ('ASC_H', models.BooleanField(default=False, verbose_name='非典型鳞状细胞不除外上皮高度病')),
                ('AGC_NSL_CC', models.BooleanField(default=False, verbose_name='非典型腺细胞(无具体指向)宫颈管')),
                ('AGC_NSL_E', models.BooleanField(default=False, verbose_name='非典型腺细胞(无具体指向)宫内膜')),
                ('AGC_NSL_US', models.BooleanField(default=False, verbose_name='非典型腺细胞(无具体指向)不能确定来源')),
                ('LSIL', models.BooleanField(default=False, verbose_name='鳞状上皮内低度病变')),
                ('AGC_FN_CC', models.BooleanField(default=False, verbose_name='非典型腺细胞(倾向瘤变)宫颈管')),
                ('AGC_FN_US', models.BooleanField(default=False, verbose_name='非典型腺细胞(倾向瘤变)不能确定来源')),
                ('HSIL', models.BooleanField(default=False, verbose_name='鳞状上皮内高度病变')),
                ('AIS', models.BooleanField(default=False, verbose_name='颈管原位癌')),
                ('SCC', models.BooleanField(default=False, verbose_name='鳞状细胞癌')),
                ('GC_CC', models.BooleanField(default=False, verbose_name='腺癌宫颈管')),
                ('GC_E', models.BooleanField(default=False, verbose_name='腺癌宫内膜')),
                ('GC_OT', models.BooleanField(default=False, verbose_name='腺癌其他')),
                ('OTHER', models.BooleanField(default=False, verbose_name='其他恶性肿瘤')),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='pathology.diagnosis', verbose_name='诊断')),
                ('labelitems', models.ManyToManyField(blank=True, to='pathology.LabelItem', verbose_name='标注')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告集',
            },
        ),
        migrations.CreateModel(
            name='PathologyPictureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologyPicture', models.FileField(upload_to='origin_images', verbose_name='病理图片')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='图片上传时间')),
                ('description', models.TextField(verbose_name='图片描述')),
                ('isCutted', models.BooleanField(default=False, verbose_name='是否已经切图')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathologypictures', to='pathology.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '病理图片',
                'verbose_name_plural': '病理图片集',
            },
        ),
        migrations.AddField(
            model_name='diagnosisitem',
            name='pathologyPicture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology.pathologypictureitem', verbose_name='病理图片'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='pathology.patient', verbose_name='患者'),
        ),
    ]
