# Generated by Django 3.2.5 on 2021-12-30 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='诊断创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='诊断更新时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='诊断描述')),
                ('isFinished', models.BooleanField(default=False, verbose_name='诊断是否完成')),
                ('doctors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='医生')),
            ],
            options={
                'verbose_name': '诊断',
                'verbose_name_plural': '诊断集',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='诊断项创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='诊断项更新时间')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology.diagnosis', verbose_name='诊断')),
            ],
            options={
                'verbose_name': '诊断项',
                'verbose_name_plural': '诊断项集',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='病人姓名')),
                ('sex', models.CharField(max_length=255, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '病人',
                'verbose_name_plural': '病人集',
            },
        ),
        migrations.CreateModel(
            name='PathologyPictureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologyPicture', models.FileField(upload_to='', verbose_name='病理图片')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='图片上传时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图片描述')),
                ('isCutted', models.BooleanField(default=False, verbose_name='是否已经切图')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '病理图片',
                'verbose_name_plural': '病理图片集',
            },
        ),
        migrations.CreateModel(
            name='LabelItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='标注时间')),
                ('modifiedAt', models.DateTimeField(auto_now=True, verbose_name='标注更新时间')),
                ('category', models.CharField(choices=[('M', '真菌')], default='M', max_length=4, verbose_name='类别')),
                ('x', models.FloatField(verbose_name='标注起点坐标X')),
                ('y', models.FloatField(verbose_name='标注起点坐标Y')),
                ('w', models.FloatField(verbose_name='标注宽度')),
                ('h', models.FloatField(verbose_name='标注高度')),
                ('zoomLevel', models.FloatField(default=10.0, verbose_name='标注时放大倍数')),
                ('regionPicture', models.FileField(blank=True, null=True, upload_to='', verbose_name='标注区域图')),
                ('diagnosisItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology.diagnosisitem', verbose_name='诊断项')),
            ],
            options={
                'verbose_name': '标注',
                'verbose_name_plural': '标注集',
            },
        ),
        migrations.AddField(
            model_name='diagnosisitem',
            name='pathologyPicture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology.pathologypictureitem', verbose_name='病理图片'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology.patient', verbose_name='患者'),
        ),
    ]
