# Generated by Django 3.2.5 on 2022-01-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='pathology.patient', verbose_name='患者'),
        ),
        migrations.AlterField(
            model_name='diagnosisitem',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pathology.diagnosis', verbose_name='诊断'),
        ),
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='description',
            field=models.TextField(verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='pathologyPicture',
            field=models.FileField(upload_to='origin_images', verbose_name='病理图片'),
        ),
    ]
