# Generated by Django 3.2.5 on 2021-12-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologypictureitem',
            name='isCutted',
            field=models.BooleanField(default=False, verbose_name='是否已经切图'),
        ),
    ]
