# Generated by Django 3.2.5 on 2022-02-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_report_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='图片描述'),
        ),
    ]
