# Generated by Django 3.2.5 on 2021-12-13 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_pathologypictureitem_iscutted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='标注时间')),
                ('modifiedAt', models.DateTimeField(auto_now=True, verbose_name='标注更新时间')),
                ('category', models.CharField(choices=[('M', '真菌')], default='M', max_length=4, verbose_name='类别')),
                ('x', models.FloatField(verbose_name='标注起点坐标X')),
                ('y', models.FloatField(verbose_name='标注起点坐标Y')),
                ('w', models.FloatField(verbose_name='标注宽度')),
                ('h', models.FloatField(verbose_name='标注高度')),
                ('zoomLevel', models.FloatField(verbose_name='标注时放大倍数')),
                ('pathologypictureitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology.pathologypictureitem', verbose_name='诊断')),
            ],
            options={
                'verbose_name': '标注',
                'verbose_name_plural': '标注集',
            },
        ),
    ]
