# Generated by Django 3.2.5 on 2022-01-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_labelitem_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelitem',
            name='confidence',
            field=models.FloatField(default=1.0, verbose_name='自信度'),
        ),
    ]
