# Generated by Django 3.2.5 on 2021-12-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_labelitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelitem',
            name='regionPicture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='标注区域图'),
        ),
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='pathologyPicture',
            field=models.FileField(upload_to='', verbose_name='病理图片'),
        ),
    ]
