# Generated by Django 3.2.5 on 2022-01-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0004_labelitem_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelitem',
            name='diagnosisItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pathology.diagnosisitem', verbose_name='诊断项'),
        ),
        migrations.AlterField(
            model_name='labelitem',
            name='regionPicture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='标注区域图'),
        ),
    ]
