# Generated by Django 3.2.5 on 2022-01-12 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0005_auto_20220112_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathologypictures', to='pathology.patient', verbose_name='患者'),
        ),
    ]
