# Generated by Django 3.2.5 on 2022-01-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0006_alter_pathologypictureitem_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='报告时间')),
                ('modifiedAt', models.DateTimeField(auto_now=True, verbose_name='报告更新时间')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='pathology.diagnosis', verbose_name='诊断')),
                ('labelitems', models.ManyToManyField(to='pathology.LabelItem', verbose_name='标注')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告集',
            },
        ),
    ]
