# Generated by Django 3.2.5 on 2022-01-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0007_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelitem',
            name='category',
            field=models.CharField(choices=[('M', '真菌'), ('TR', '阴道滴虫'), ('AM', '放线菌'), ('CL', '线索细胞'), ('CMV', '巨细胞病毒'), ('HSV', '疱疹病毒'), ('IM', '炎症'), ('S', '萎缩'), ('ASC-US', '非典型鳞状细胞意义不明'), ('ASC-H', '非典型鳞状细胞不除外上皮高度病'), ('AGC(NSL)-CC', '非典型腺细胞(无具体指向)宫颈管'), ('AGC(NSL)-E', '非典型腺细胞(无具体指向)宫内膜'), ('AGC(NSL)-US', '非典型腺细胞(无具体指向)不能确定来源'), ('LSIL', '鳞状上皮内低度病变'), ('AGC(FN)-CC', '非典型腺细胞(倾向瘤变)宫颈管'), ('AGC(FN)-US', '非典型腺细胞(倾向瘤变)不能确定来源'), ('HSIL', '鳞状上皮内高度病变'), ('AIS', '颈管原位癌'), ('SCC', '鳞状细胞癌'), ('GC-CC', '腺癌宫颈管'), ('GC-E', '腺癌宫内膜'), ('GC-OT', '腺癌其他')], default='M', max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diagnosis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='pathology.diagnosis', verbose_name='诊断'),
        ),
        migrations.AlterField(
            model_name='report',
            name='labelitems',
            field=models.ManyToManyField(blank=True, to='pathology.LabelItem', verbose_name='标注'),
        ),
    ]
